image:
    name: checkmarx/kics:latest
    entrypoint: [""]

stages:
    - kics

kics-scan:
    stage: kics
    script:
        - kics scan --no-progress -p ./gcp -o ./gcp --report-formats pdf --output-name kics-results
    artifacts:
        name: kics-results.pdf
        paths:
            - ./gcp/kics-results.pdf
        when: always
